name: Hourly Weather Collector
on:
  schedule:
    - cron: "3 * * * *"      # 每小时第3分
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}
          QWEATHER_LOCATION: "440300"
        run: |
          python collect_weather.py
          echo "--- after run, list files ---"
          ls -lah
          echo "--- show first lines if exists ---"
          [ -f weather_log.csv ] && head -n 5 weather_log.csv || (echo "weather_log.csv NOT FOUND" && exit 1)

      - name: Git status (debug)
        run: |
          git status --porcelain || true

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weather_log.csv weather_log.sqlite3 || true
          git commit -m "data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push || echo "No push (maybe no changes)"
