name: Hourly Weather Collector

on:
  schedule:
    - cron: "3 * * * *"   # 每小时第 3 分
  workflow_dispatch:

# 关键：给 GITHUB_TOKEN 写权限（否则无法 push）
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 方便 push；默认 true，这里显式写上
          persist-credentials: true
          # 拿到完整历史，有些仓库策略需要
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          QWEATHER_API_KEY: ${{ secrets.QWEATHER_API_KEY }}   # 没配也没关系
          QWEATHER_LOCATION: "440300"
        run: |
          python collect_weather.py

          echo "--- list files (after run) ---"
          ls -lah

          echo "--- preview csv ---"
          if [ -f weather_log.csv ]; then
            head -n 5 weather_log.csv
          else
            echo "weather_log.csv NOT FOUND"
            exit 1
          fi

      - name: Git status (debug)
        run: |
          git status --porcelain || true
          git log -1 --oneline || true

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weather_log.csv
          git commit -m "data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push


      # 兜底：就算 push 失败，也把文件作为 Artifact 可下载
      - name: Upload CSV artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: weather_log
          path: weather_log.csv
